[package]
name = "riplog"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
ctrlc = "3"
env_logger = "0.11.10"
humanize-bytes = "1.0.6"
log = "0.4.29"
memchr = "2"
rapidhash = "1"
regex = "1"
smallvec = "1"
smartstring = "1.0.1"
vecmap-rs = "0.2.4"

[dev-dependencies]
proptest = "1"
logfmt = "0.0.2"
